// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb7OusOkzjmN_5T3qZ_kP0zrAOqIFZ5Hg',
    appId: '1:1031082553469:web:ec25a93d50ec42a98b0114',
    messagingSenderId: '1031082553469',
    projectId: 'task-tracker-d5cef',
    authDomain: 'task-tracker-d5cef.firebaseapp.com',
    storageBucket: 'task-tracker-d5cef.firebasestorage.app',
    measurementId: 'G-34DQBLVDFR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMDRM4Qajakzgu181Q7x9xTvWFQRHfyPA',
    appId: '1:1031082553469:ios:60bfb246c185960a8b0114',
    messagingSenderId: '1031082553469',
    projectId: 'task-tracker-d5cef',
    storageBucket: 'task-tracker-d5cef.firebasestorage.app',
    iosClientId:
        '1031082553469-jm42g6vjnqolts32p3v39m17evdqj6ap.apps.googleusercontent.com',
    iosBundleId: 'com.tattoopop.tasktracker.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb7OusOkzjmN_5T3qZ_kP0zrAOqIFZ5Hg',
    appId: '1:1031082553469:web:ebd7943118e4947e8b0114',
    messagingSenderId: '1031082553469',
    projectId: 'task-tracker-d5cef',
    authDomain: 'task-tracker-d5cef.firebaseapp.com',
    storageBucket: 'task-tracker-d5cef.firebasestorage.app',
    measurementId: 'G-D90J9GE19E',
  );
}
